[package]
name = "akari_macro"
version = "0.1.0"
edition = "2024"

[dependencies] 
syn = { version = "1.0", features = ["full", "extra-traits"] }
quote = "1.0"
proc-macro2 = "1.0" 

[lib]
proc-macro = true
